image: docker:19.03.12

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: $DOCKER_HUB_ID/email-service
  CONTAINER_NAME: email-service
  ENVIROMENT: staging

build:
  stage: build
  script:
    - docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PASSWORD
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  environment:
    name: $ENVIROMENT

deploy:
  stage: deploy
  script:
    - apk upgrade && apk update
    - apk add openssh-client
    - apk add sshpass
    - sshpass -p "$USER_PASSWORD" ssh -o StrictHostKeyChecking=no $USER_ID@$STAGING_SERVER docker pull $IMAGE_NAME
    - sshpass -p "$USER_PASSWORD" ssh -o StrictHostKeyChecking=no $USER_ID@$STAGING_SERVER "docker stop $CONTAINER_NAME || true"
    - sshpass -p "$USER_PASSWORD" ssh -o StrictHostKeyChecking=no $USER_ID@$STAGING_SERVER docker run --rm -d -p 80:8080 --name $CONTAINER_NAME $IMAGE_NAME
  environment:
    name: $ENVIROMENT
    url: $STAGING_SERVER
