image: docker:19.03.12

stages:
  - test
  - build
  - deploy

variables:
  CONTAINER_NAME: email-service
  ENVIRONMENT: dev

test:
  image: gradle:6.9.0-jdk11
    stage: test
    script:
      - gradle test jacocoTestReport
    artifacts:
      paths:
        - build/jacoco/jacoco.xml

build:
  image: gradle:6.9.0-jdk11
  stage: build
  script:
    - gradle build -x test
  artifacts:
    paths:
      - build/libs/*.jar

build-docker-image:
  stage: build
  script:
    - docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PASSWORD
    - docker build -t $DOCKER_HUB_ID/$IMAGE_NAME .
    - docker push $DOCKER_HUB_ID/$IMAGE_NAME
  environment:
    name: $ENVIRONMENT

deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_HUB_ID/$IMAGE_NAME
    - "{ docker stop $CONTAINER_NAME; docker rm $CONTAINER_NAME; } || true"
    - "docker run -d -p $EMAIL_SERVICE_PORT:$EMAIL_SERVICE_PORT \
    --network $DOCKER_NETWORK \
    --name $CONTAINER_NAME \
    -e spring.profiles.active=$ENVIRONMENT \
    -e HOST=$HOST \
    -e EUREKA_SERVER=$EUREKA_SERVER \
    -e KAFKA_SERVER=$KAFKA_SERVER \
    $DOCKER_HUB_ID/$IMAGE_NAME"

  environment:
    name: $ENVIRONMENT
    url: $DEV_SERVER