spring:
  application:
    name: email-service
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
aws:
  ses:
    credentials:
      access-key: AKIAYVRYD5CWBAESNBHL
      secret-key: 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
kafka:
  bootstrap:
    servers: 127.0.0.1:9092