server:
  port: 30030

spring:
  application:
    name: email-service

eureka:
  instance:
    prefer-ip-address: true
    ip-address: "${HOST_IP}"

springfox:
  documentation:
    swagger:
      v2:
        path: /email-service/v2/api-docs