spring:
  application:
    name: email-service
eureka:
  instance:
    prefer-ip-address: true
    ip-address: "${HOST}"
  client:
    serviceUrl:
      defaultZone: http://139.150.75.239:8761/eureka/
server:
  port: 8080
aws:
  ses:
    credentials:
      access-key: AKIAYVRYD5CWBAESNBHL
      secret-key: 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
kafka:
  bootstrap:
    servers: 139.150.75.240:9092