spring:
  application:
    name: email-service
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0
aws:
  ses:
    region: ap-northeast-2
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
kafka:
  bootstrap:
    servers: 127.0.0.1:9092