spring:
  application:
    name: email-service
eureka:
  instance:
    prefer-ip-address: true
    ip-address: "${HOST}"
    non-secure-port: 8080
  client:
    serviceUrl:
      defaultZone: "http://${EUREKA_SERVER}/eureka/"
server:
  port: 30030
aws:
  ses:
    credentials:
      access-key: AKIAYVRYD5CWIFT3XZVI
      secret-key: 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
kafka:
  bootstrap:
    servers: "${KAFKA_SERVER}"